//@ pragma UseQApplication
import QtQuick
import Quickshell
import qs.Modules.Panel
import qs.Modules.OSD
import qs.Modules.Wallpaper
import qs.Modules.SysTray
import qs.Services
import qs.Commons

ShellRoot {
  Component.onCompleted: {
    // this is generated by `chafa --colors none -f symbols --symbols braille --view-size 50x50 taijibagua.png`
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⣡⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣌⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢟⣵⣾⠿⣿⣿⡉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⢉⣿⡿⢿⣷⣮⡻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢋⣵⣿⠟⠁⠀⣹⣿⣷⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣾⣿⣅⠀⠙⠿⣿⣮⡙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⡿⢋⣴⣿⠟⠁⠀⣠⣾⠟⢹⣿⣧⠀⠀⠀⠀⠀⣿⡗⠀⠀⠀⠀⢀⣾⣿⠋⠻⣷⣄⠀⠉⠻⣿⣦⡙⢿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⡿⣫⣾⡿⠛⠁⢀⣴⣾⠟⠁⢀⣠⣿⣿⣿⠿⠿⠿⠿⠿⠿⠿⠿⠿⢿⣿⣿⣷⣄⠀⠈⠻⣷⣤⣾⡿⠻⣿⣷⣝⢿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⠟⣡⣾⡿⠋⠀⢀⣴⡿⠛⠁⢀⣴⣾⠟⠁⢻⣿⣧⣀⣀⣀⣀⣀⣀⣀⣀⣼⣿⡏⠈⠻⣷⣄⣠⣾⡿⣿⣦⡀⠀⠙⢿⣷⣌⠻⣿⣿⣿");
    Logger.i("Shell", "⣿⠟⣡⣾⡿⠋⠀⢀⣴⡿⠋⠀⢀⣴⣿⣿⣅⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⢀⣨⣿⣿⣧⡀⠀⠙⢿⣦⡀⠀⠙⢿⣷⣌⠻⣿");
    Logger.i("Shell", "⣿⢀⣿⣿⣿⣷⣾⣿⣏⡀⢀⣴⡿⠋⠁⠙⣿⣿⣿⣿⣿⡿⠟⠛⠋⠉⠉⠉⠛⠻⢿⣿⣿⣿⣿⣟⠁⠈⠻⢿⣦⡀⢀⣹⣿⣶⣾⣿⣿⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⡇⠀⢹⣿⠻⢿⣿⣿⣿⣦⣤⣴⣿⣿⣿⣿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⣿⣷⣤⣤⣴⣿⣿⣿⡿⠿⣿⡏⠁⢀⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⡇⠀⢸⣿⠀⠀⢹⣿⠛⠻⣿⣿⣿⣿⡿⠁⢀⣠⣤⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⠟⠛⢿⣿⠀⠀⣿⡇⠀⢀⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⡇⠀⢸⣿⠀⠀⢹⣿⠀⠀⣿⣿⣿⣿⢁⣾⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⠀⠀⢹⣿⠀⠀⣿⡇⠀⢀⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⣷⣶⣾⣿⣶⣶⣿⣿⠀⠀⣿⣿⣿⡏⢸⣿⣿⣿⠁⢹⣿⣿⣿⠀⠀⠀⢾⣿⠆⠀⠀⠀⢿⣿⣿⣿⠀⠀⢹⣿⠀⠀⣿⣷⣶⣾⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⠂⠀⢸⣿⠀⠀⢺⣿⠀⠀⣿⣿⣿⣿⡘⣿⣿⣿⣿⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⣠⢃⣿⣿⣿⣿⠀⠀⢹⣿⠀⠀⣿⡇⠀⢸⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⠁⠀⢸⣿⠀⠀⢹⣿⣀⣠⣿⣿⣿⣿⣧⡙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⣤⣶⣾⢇⣼⣿⣿⣿⣿⣤⣀⢹⣿⠀⠀⣿⡇⠀⢸⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⠁⠀⢸⣿⣠⣴⣿⣿⣿⠟⠛⠻⢿⣿⣿⣷⣌⡻⢿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢟⣡⣾⣿⣿⣿⠟⠛⠻⣿⣿⣿⣦⣤⣿⡇⠀⢸⣿⡇⣿");
    Logger.i("Shell", "⣿⢀⣿⣷⣶⡿⠿⣿⣍⠁⠈⠻⣷⣄⡀⣠⣿⣿⣿⣿⣿⣶⣬⣍⣛⣛⣛⣛⣩⣥⣶⣿⣿⣿⣿⠟⠁⠀⣠⣾⠟⠋⠉⣛⣿⡿⣿⣶⣾⣿⡇⣿");
    Logger.i("Shell", "⣿⣬⡻⣿⣷⣄⠀⠈⠻⣷⣄⠀⠈⣻⣿⣿⡋⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠁⢀⣤⣾⠟⠁⠀⣠⣾⠿⠋⠀⣠⣽⣿⢟⣥⣿");
    Logger.i("Shell", "⣿⣿⣿⣮⡻⢿⣷⣄⠀⠈⠻⣷⣾⡿⠋⠙⢿⣦⡀⣼⣿⡟⠛⠛⠛⣿⣿⠛⠛⠛⢿⣿⣇⢀⣴⣿⠟⠁⠀⣠⣾⠟⠁⠀⣠⣾⡿⢟⣵⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣦⡙⢿⣿⣦⡀⠀⠙⢿⣦⡀⠀⠙⣿⣿⣿⣥⣤⣤⣤⣿⣿⣤⣤⣤⣬⣿⣿⣿⠛⠁⢀⣴⣾⠟⠁⠀⣠⣾⡿⢋⣴⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣶⣝⢿⣿⣦⡀⠀⠙⢿⣦⣰⣿⡿⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⣿⣿⣆⣴⡿⠛⠁⢀⣴⣾⡿⣫⣶⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣝⠻⣿⣦⣀⠀⢹⣿⡿⠷⠶⠶⠶⠶⠶⣶⣶⠶⠶⠶⠶⠶⠾⣿⣿⡏⠀⢀⣴⣿⠟⣫⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣌⠻⣿⣷⣿⣿⣁⣀⣀⣀⣀⣀⣀⣿⣟⢀⢀⢀⢀⢀⢀⠘⣿⣿⣴⣿⠟⣡⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⡻⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⢟⣵⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿");
    Logger.i("Shell", "          Yin and Yang in One. Tai Ji Pan.          ");
  }

  property bool settingsLoaded: false

  Connections {
    target: Settings ? Settings : null
    function onSettingsLoaded() {
      settingsLoaded = true;
    }
  }

  Connections {
    target: Quickshell
    function onReloadCompleted() {
      Quickshell.inhibitReloadPopup();
    }
    function onReloadFailed() {
      if (Settings.isLoaded && !Settings.data.debug) {
        Quickshell.inhibitReloadPopup();
      }
    }
  }

  Loader {
    active: settingsLoaded
    sourceComponent: Item {
      Component.onCompleted: {
        AppThemeService.init();
        ImageCacheService.init();
        WallpaperService.init();

        Qt.callLater(() => {
          IPCService.init();
        });

        Logger.i("Shell", "All services loaded, shell initialization complete");
      }

      Panel {}
      OSD {}
      Overview {}
      Wallpaper {}

      SysTray {}
    }
  }
}
